services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ChatDb: "Host=host.docker.internal;Port=5432;Database=ChatDb;Username=SA;Password=Qwerty12"
      Jwt__SecretKey: "Dev_Only_Signing_Key_Do_Not_Use_In_Prod_2026"
      Jwt__Issuer: "SignalChat"
      Jwt__Audience: "SignalChat"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - backend-images:/app/wwwroot/images

  frontend:
    build:
      context: ./frontend
    environment:
      BACKEND_BASE_URL: "http://backend:8080"
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend-images:
